# Generated by Django 3.2.7 on 2021-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auth_token',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
