# Generated by Django 3.2.7 on 2021-09-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_app', '0003_auto_20210909_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
